steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/helloworld-docker-repo/cloudbuild_gke:tag1', '.' ]
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/helloworld-docker-repo/cloudbuild_gke:tag1'
    id: Push
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=deployment.yaml
    - --location=us-central1
    - --cluster=autopilot-cluster
